/**
  **************************************************************************
  * @file     wk_hx71708.c
  * @brief    interrupt-driven driver for two HX71708 load-cell ADCs
  *
  * HX71708 LL (left):  PD_SCK_LL_PIN, DOUT_LL_PIN, EXINT_LINE_4
  * HX71708 RR (right): PD_SCK_RR_PIN, DOUT_RR_PIN, EXINT_LINE_1
  * (pin/port macros generated by the workbench in at32f425_wk_config.h;
  * exint line/edge config lives in wk_exint.c)
  *
  * Protocol is the same 2-wire clocked-serial family as HX711, but with
  * HX71708-specific numbers taken from its datasheet:
  *  - single channel, fixed gain 128 (no channel/gain select pulses)
  *  - pulses 25-28 after the 24 data bits select the *next* conversion's
  *    output rate (25=10Hz/26=20Hz/27=80Hz/28=320Hz); at least 25 pulses
  *    are required every read. This driver always sends exactly 25, which
  *    keeps the chip at its default 10Hz rate.
  *  - PD_SCK high time must stay under 50us during normal clocking (vs
  *    HX711's ~60us), so the 1us half-clock used here has plenty of margin.
  *  - native output is two's complement (same as HX711), so the existing
  *    sign-extension logic applies unchanged.
  *  - datasheet requires a one-time init pulse (PD_SCK high >100us, then
  *    low) after MCU power-up before the first conversion, and recommends
  *    the same pulse to force-reset a channel if DOUT ever gets stuck high
  *    past the expected conversion period.
  *
  * DOUT idles high and drops low the instant a conversion is ready, so
  * that transition is wired as a falling-edge exint (wk_exint.c) on each
  * channel's DOUT pin.
  *
  * wk_hx71708_dout_isr() does the absolute minimum on that edge: mask
  * the channel's own exint line, clear the pending flag, set a "ready"
  * hint. It does NOT clock the data out itself. wk_hx71708_get_sample(),
  * called every main loop tick, is what actually does the (~50us
  * blocking) clock-out and re-arms the line afterwards.
  *
  * That split matters on this board: DOUT/PD_SCK have no external pull
  * or series resistor (bare mcu-to-chip traces - see schematic), and
  * PD_SCK/DOUT are adjacent pins on the hx71708 package, so a noisy or
  * floating line is a real possibility, not just a theoretical one.
  * Because the isr masks on the very first edge and does nothing else,
  * a channel that starts oscillating - however fast, however bursty -
  * can cost at most one isr entry per masked episode: with inten
  * cleared, the hardware itself guarantees no further dispatches for
  * that line until wk_hx71708_get_sample() deliberately re-arms it.
  * (An earlier version clocked out data directly from the isr and only
  * rate-limited/circuit-broke per edge; a burst of edges too short to
  * trip that breaker but frequent enough overall could still saturate
  * the cpu. Masking unconditionally on first edge has no such gap.)
  **************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "wk_hx71708.h"
#include "wk_gpio.h"
#include "wk_system.h"

typedef struct
{
  gpio_type *sck_port;
  uint16_t   sck_pin;
  gpio_type *dout_port;
  uint16_t   dout_pin;
  uint32_t   exint_line;
} hx71708_pins_type;

static const hx71708_pins_type hx71708_pins[HX71708_CH_NUM] =
{
  { PD_SCK_LL_GPIO_PORT, PD_SCK_LL_PIN, DOUT_LL_GPIO_PORT, DOUT_LL_PIN, EXINT_LINE_4 },  /* HX71708 LL */
  { PD_SCK_RR_GPIO_PORT, PD_SCK_RR_PIN, DOUT_RR_GPIO_PORT, DOUT_RR_PIN, EXINT_LINE_1 },  /* HX71708 RR */
};

/* set by wk_hx71708_dout_isr() the instant dout falls (and the line is
   masked); cleared by wk_hx71708_get_sample(), which does the actual
   clock-out and re-arms the line. The isr never touches hardware other
   than mask/clear, and never loops, so its cost is fixed regardless of
   how the line behaves afterwards. */
static volatile uint8_t hx71708_ready_hint[HX71708_CH_NUM];

/* tick reference for wk_hx71708_check_stale(), stamped by every successful
   get_sample() and by every forced reset */
static uint32_t hx71708_last_activity_ticks[HX71708_CH_NUM];

/* datasheet: PD_SCK held high >100us forces an ADC (re)init/reset */
#define HX71708_RESET_PULSE_US            (uint32_t)(150)

/* longest gap allowed between samples before a channel is declared stuck
   and force-reset; generous margin over the 100ms period at the chip's
   default 10hz rate */
#define HX71708_STALE_TIMEOUT_US          (uint32_t)(500000)

/* shortest gap allowed between accepted samples: well under the 100ms/
   10hz period, but guards against a floating/noisy dout line producing
   a "ready" hint faster than a real chip ever could (e.g. a loose
   connection or a dead sensor). Checked in wk_hx71708_get_sample():
   a hint arriving sooner than this is dropped there (no shift_in),
   and the line is simply re-armed for the next one. */
#define HX71708_MIN_SAMPLE_INTERVAL_US    (uint32_t)(20000)

/**
  * @brief  pull a channel's PD_SCK high for the datasheet's init/reset
  *         hold time, then back low. Required once after MCU power-up
  *         before the first conversion, and safe to reuse any time the
  *         channel needs to be force-reset (e.g. DOUT stuck high).
  *         Masks the channel's own dout exint line for the duration,
  *         since the pulse can make DOUT bounce.
  * @param  ch: hx71708 channel to reset
  * @retval none
  */
static void hx71708_reset_pulse(hx71708_channel_type ch)
{
  exint_interrupt_enable(hx71708_pins[ch].exint_line, FALSE);

  gpio_bits_set(hx71708_pins[ch].sck_port, hx71708_pins[ch].sck_pin);
  wk_delay_us(HX71708_RESET_PULSE_US);
  gpio_bits_reset(hx71708_pins[ch].sck_port, hx71708_pins[ch].sck_pin);

  hx71708_ready_hint[ch] = 0;
  exint_flag_clear(hx71708_pins[ch].exint_line);
  exint_interrupt_enable(hx71708_pins[ch].exint_line, TRUE);

  wk_tick_elapsed_us(&hx71708_last_activity_ticks[ch], 0);
}

/**
  * @brief  configure the sck (output) and dout (input) pins for both
  *         channels, then run the power-up init pulse each chip needs
  *         before its first conversion.
  * @param  none
  * @retval none
  */
void wk_hx71708_init(void)
{
  gpio_init_type gpio_init_struct;
  uint8_t i;

  gpio_default_para_init(&gpio_init_struct);

  for(i = 0; i < HX71708_CH_NUM; i++)
  {
    /* sck: push-pull output, idle low */
    gpio_bits_reset(hx71708_pins[i].sck_port, hx71708_pins[i].sck_pin);
    gpio_init_struct.gpio_drive_strength = GPIO_DRIVE_STRENGTH_MODERATE;
    gpio_init_struct.gpio_out_type = GPIO_OUTPUT_PUSH_PULL;
    gpio_init_struct.gpio_mode = GPIO_MODE_OUTPUT;
    gpio_init_struct.gpio_pins = hx71708_pins[i].sck_pin;
    gpio_init_struct.gpio_pull = GPIO_PULL_NONE;
    gpio_init(hx71708_pins[i].sck_port, &gpio_init_struct);

    /* dout: input with weak pull-up (defined idle-high state when the
       sensor is unpowered/disconnected; a driven hx71708 output overrides it) */
    gpio_init_struct.gpio_mode = GPIO_MODE_INPUT;
    gpio_init_struct.gpio_pins = hx71708_pins[i].dout_pin;
    gpio_init_struct.gpio_pull = GPIO_PULL_UP;
    gpio_init(hx71708_pins[i].dout_port, &gpio_init_struct);
  }

  for(i = 0; i < HX71708_CH_NUM; i++)
  {
    hx71708_ready_hint[i] = 0;
    hx71708_reset_pulse((hx71708_channel_type)i);
  }
}

/**
  * @brief  clock out a 24-bit conversion assuming the channel is already
  *         known to be ready. Sends the minimum 25 sck pulses, which keeps
  *         the chip at its default 10hz output rate for the next
  *         conversion (see file header).
  * @param  ch: hx71708 channel to shift in
  * @retval sign-extended 24-bit result
  */
static int32_t hx71708_shift_in(hx71708_channel_type ch)
{
  gpio_type *sck_port  = hx71708_pins[ch].sck_port;
  uint16_t   sck_pin   = hx71708_pins[ch].sck_pin;
  gpio_type *dout_port = hx71708_pins[ch].dout_port;
  uint16_t   dout_pin  = hx71708_pins[ch].dout_pin;
  uint32_t value = 0;
  uint8_t i;

  for(i = 0; i < 24; i++)
  {
    gpio_bits_set(sck_port, sck_pin);
    wk_delay_us(1);
    value = (value << 1) | gpio_input_data_bit_read(dout_port, dout_pin);
    gpio_bits_reset(sck_port, sck_pin);
    wk_delay_us(1);
  }

  /* 25th pulse: minimum required, selects 10hz output rate for the next
     conversion */
  gpio_bits_set(sck_port, sck_pin);
  wk_delay_us(1);
  gpio_bits_reset(sck_port, sck_pin);
  wk_delay_us(1);

  /* sign-extend the 24-bit two's complement value */
  if(value & 0x00800000)
  {
    value |= 0xFF000000;
  }

  return (int32_t)value;
}

/**
  * @brief  dout falling-edge exint isr entry point. Does the minimum
  *         possible and returns: mask the channel's own exint line so
  *         no further edge on it can dispatch this vector again, clear
  *         the pending flag, and set the ready hint. No shift_in here -
  *         that's wk_hx71708_get_sample()'s job, from the main loop.
  *
  *         Because the line is masked unconditionally on this very
  *         first edge, a channel that starts oscillating - at any rate,
  *         in any burst pattern - cannot generate a second isr entry
  *         until wk_hx71708_get_sample() deliberately re-arms it. That
  *         bounds the isr's contribution to one entry per masked
  *         episode, with no dependence on how fast or bursty the real
  *         edges are.
  * @param  ch: hx71708 channel whose dout line just fell
  * @retval none
  */
void wk_hx71708_dout_isr(hx71708_channel_type ch)
{
  exint_interrupt_enable(hx71708_pins[ch].exint_line, FALSE);
  exint_flag_clear(hx71708_pins[ch].exint_line);
  hx71708_ready_hint[ch] = 1;
}

/**
  * @brief  service ch's ready hint (if any): clock out the conversion
  *         and re-arm the line for the next edge. Call every main loop
  *         iteration for both channels - this is where the ~50us
  *         blocking clock-out actually happens, deliberately kept out
  *         of isr context (see file header).
  *
  *         If the hint arrived less than HX71708_MIN_SAMPLE_INTERVAL_US
  *         after the last accepted sample (a real hx71708 can't convert
  *         that fast - a floating/noisy dout line producing edges way
  *         faster than the chip's 10hz rate), it's dropped without a
  *         shift_in: the line is still re-armed either way, so a noisy
  *         channel just costs one bounded ~cycle - isr entry, then this
  *         cheap check - per hint, never more, regardless of how the
  *         line behaves in between.
  * @param  ch: hx71708 channel to read
  * @param  raw_value: filled with the sign-extended 24-bit result, only
  *         valid when this returns 1
  * @retval 1 if a new sample was accepted (and *raw_value filled),
  *         0 otherwise (nothing pending, or the hint was dropped as
  *         too-soon)
  */
uint8_t wk_hx71708_get_sample(hx71708_channel_type ch, int32_t *raw_value)
{
  uint8_t accepted = 0;

  if(!hx71708_ready_hint[ch])
  {
    return 0;
  }
  hx71708_ready_hint[ch] = 0;

  if(wk_tick_elapsed_us(&hx71708_last_activity_ticks[ch], HX71708_MIN_SAMPLE_INTERVAL_US))
  {
    *raw_value = hx71708_shift_in(ch);
    accepted = 1;
  }

  exint_flag_clear(hx71708_pins[ch].exint_line);
  exint_interrupt_enable(hx71708_pins[ch].exint_line, TRUE);

  return accepted;
}

/**
  * @brief  force-reset a channel that has gone too long without producing
  *         a sample (datasheet-recommended recovery for a DOUT stuck
  *         high, e.g. sensor disconnected or missed edge).
  * @param  ch: hx71708 channel to check
  * @retval 1 if the channel was stale and has just been force-reset,
  *         0 if it's still within its normal sample period
  */
uint8_t wk_hx71708_check_stale(hx71708_channel_type ch)
{
  if(wk_tick_elapsed_us(&hx71708_last_activity_ticks[ch], HX71708_STALE_TIMEOUT_US) == 0)
  {
    return 0;
  }

  hx71708_reset_pulse(ch);
  return 1;
}
