/**
  **************************************************************************
  * @file     wk_hx71708.c
  * @brief    bit-banged driver for two HX71708 load-cell ADCs
  *
  * HX71708 LL (left):  PD_SCK_LL_PIN, DOUT_LL_PIN
  * HX71708 RR (right): PD_SCK_RR_PIN, DOUT_RR_PIN
  * (pin/port macros generated by the workbench in at32f425_wk_config.h)
  *
  * Protocol is the same 2-wire clocked-serial family as HX711, but with
  * HX71708-specific numbers taken from its datasheet:
  *  - single channel, fixed gain 128 (no channel/gain select pulses)
  *  - pulses 25-28 after the 24 data bits select the *next* conversion's
  *    output rate (25=10Hz/26=20Hz/27=80Hz/28=320Hz); at least 25 pulses
  *    are required every read. This driver always sends exactly 25, which
  *    keeps the chip at its default 10Hz rate.
  *  - PD_SCK high time must stay under 50us during normal clocking (vs
  *    HX711's ~60us), so the 1us half-clock used here has plenty of margin.
  *  - native output is two's complement (same as HX711), so the existing
  *    sign-extension logic applies unchanged.
  *  - datasheet requires a one-time init pulse (PD_SCK high >100us, then
  *    low) after MCU power-up before the first conversion, and recommends
  *    the same pulse to force-reset a channel if DOUT ever gets stuck high
  *    past the expected conversion period.
  *
  * Note: DOUT_LL/DOUT_RR are also wired to EXINT4/EXINT1 (see wk_exint.c),
  * but that path is currently just a no-op ISR left by the workbench.
  * This driver reads the pins directly (polling), independent of it.
  **************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "wk_hx71708.h"
#include "wk_gpio.h"
#include "wk_system.h"

typedef struct
{
  gpio_type *sck_port;
  uint16_t   sck_pin;
  gpio_type *dout_port;
  uint16_t   dout_pin;
} hx71708_pins_type;

static const hx71708_pins_type hx71708_pins[HX71708_CH_NUM] =
{
  { PD_SCK_LL_GPIO_PORT, PD_SCK_LL_PIN, DOUT_LL_GPIO_PORT, DOUT_LL_PIN },  /* HX71708 LL */
  { PD_SCK_RR_GPIO_PORT, PD_SCK_RR_PIN, DOUT_RR_GPIO_PORT, DOUT_RR_PIN },  /* HX71708 RR */
};

/* number of times wk_hx71708_read_raw() polls is_ready() before giving up */
#define HX71708_READY_TIMEOUT_LOOPS       (uint32_t)(500000)

/* datasheet: PD_SCK held high >100us forces an ADC (re)init/reset */
#define HX71708_RESET_PULSE_US            (uint32_t)(150)

/**
  * @brief  pull a channel's PD_SCK high for the datasheet's init/reset
  *         hold time, then back low. Required once after MCU power-up
  *         before the first conversion, and safe to reuse any time the
  *         channel needs to be force-reset (e.g. DOUT stuck high).
  * @param  ch: hx71708 channel to reset
  * @retval none
  */
static void hx71708_reset_pulse(hx71708_channel_type ch)
{
  gpio_bits_set(hx71708_pins[ch].sck_port, hx71708_pins[ch].sck_pin);
  wk_delay_us(HX71708_RESET_PULSE_US);
  gpio_bits_reset(hx71708_pins[ch].sck_port, hx71708_pins[ch].sck_pin);
}

/**
  * @brief  configure the sck (output) and dout (input) pins for both
  *         channels, then run the power-up init pulse each chip needs
  *         before its first conversion.
  * @param  none
  * @retval none
  */
void wk_hx71708_init(void)
{
  gpio_init_type gpio_init_struct;
  uint8_t i;

  gpio_default_para_init(&gpio_init_struct);

  for(i = 0; i < HX71708_CH_NUM; i++)
  {
    /* sck: push-pull output, idle low */
    gpio_bits_reset(hx71708_pins[i].sck_port, hx71708_pins[i].sck_pin);
    gpio_init_struct.gpio_drive_strength = GPIO_DRIVE_STRENGTH_MODERATE;
    gpio_init_struct.gpio_out_type = GPIO_OUTPUT_PUSH_PULL;
    gpio_init_struct.gpio_mode = GPIO_MODE_OUTPUT;
    gpio_init_struct.gpio_pins = hx71708_pins[i].sck_pin;
    gpio_init_struct.gpio_pull = GPIO_PULL_NONE;
    gpio_init(hx71708_pins[i].sck_port, &gpio_init_struct);

    /* dout: input with weak pull-up (defined idle-high state when the
       sensor is unpowered/disconnected; a driven hx71708 output overrides it) */
    gpio_init_struct.gpio_mode = GPIO_MODE_INPUT;
    gpio_init_struct.gpio_pins = hx71708_pins[i].dout_pin;
    gpio_init_struct.gpio_pull = GPIO_PULL_UP;
    gpio_init(hx71708_pins[i].dout_port, &gpio_init_struct);
  }

  for(i = 0; i < HX71708_CH_NUM; i++)
  {
    hx71708_reset_pulse((hx71708_channel_type)i);
  }
}

/**
  * @brief  check whether a conversion is ready without blocking.
  * @param  ch: hx71708 channel to check
  * @retval 1 if a conversion is ready to be read, 0 otherwise
  */
uint8_t wk_hx71708_is_ready(hx71708_channel_type ch)
{
  return (gpio_input_data_bit_read(hx71708_pins[ch].dout_port, hx71708_pins[ch].dout_pin) == RESET) ? 1 : 0;
}

/**
  * @brief  clock out a 24-bit conversion assuming the channel is already
  *         known to be ready. Sends the minimum 25 sck pulses, which keeps
  *         the chip at its default 10hz output rate for the next
  *         conversion (see file header).
  * @param  ch: hx71708 channel to shift in
  * @retval sign-extended 24-bit result
  */
static int32_t hx71708_shift_in(hx71708_channel_type ch)
{
  gpio_type *sck_port  = hx71708_pins[ch].sck_port;
  uint16_t   sck_pin   = hx71708_pins[ch].sck_pin;
  gpio_type *dout_port = hx71708_pins[ch].dout_port;
  uint16_t   dout_pin  = hx71708_pins[ch].dout_pin;
  uint32_t value = 0;
  uint8_t i;

  for(i = 0; i < 24; i++)
  {
    gpio_bits_set(sck_port, sck_pin);
    wk_delay_us(1);
    value = (value << 1) | gpio_input_data_bit_read(dout_port, dout_pin);
    gpio_bits_reset(sck_port, sck_pin);
    wk_delay_us(1);
  }

  /* 25th pulse: minimum required, selects 10hz output rate for the next
     conversion */
  gpio_bits_set(sck_port, sck_pin);
  wk_delay_us(1);
  gpio_bits_reset(sck_port, sck_pin);
  wk_delay_us(1);

  /* sign-extend the 24-bit two's complement value */
  if(value & 0x00800000)
  {
    value |= 0xFF000000;
  }

  return (int32_t)value;
}

/**
  * @brief  wait for a channel to be ready (with timeout) and read a 24-bit
  *         signed sample from it. On timeout, force-resets the channel
  *         (datasheet-recommended recovery for a DOUT stuck high).
  * @param  ch: hx71708 channel to read
  * @param  raw_value: sign-extended 24-bit result, valid only on success
  * @retval 1 on success, 0 on timeout waiting for the channel to be ready
  */
uint8_t wk_hx71708_read_raw(hx71708_channel_type ch, int32_t *raw_value)
{
  uint32_t timeout = HX71708_READY_TIMEOUT_LOOPS;

  while(wk_hx71708_is_ready(ch) == 0)
  {
    if(--timeout == 0)
    {
      hx71708_reset_pulse(ch);
      return 0;
    }
  }

  *raw_value = hx71708_shift_in(ch);
  return 1;
}
